// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAsA-7EEY84ihoRQGWA1ZA31ixuzv1A-o',
    appId: '1:372015866202:web:bb08e8804469ad48531363',
    messagingSenderId: '372015866202',
    projectId: 'godevi-77a73',
    authDomain: 'godevi-77a73.firebaseapp.com',
    storageBucket: 'godevi-77a73.firebasestorage.app',
    measurementId: 'G-EE197QLDX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtoc3t_5inmv5wG3d4MUjFFD-ywOdfcXE',
    appId: '1:372015866202:android:83841a240d9e0ff3531363',
    messagingSenderId: '372015866202',
    projectId: 'godevi-77a73',
    storageBucket: 'godevi-77a73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiV8OXW2CuvnFPJZ4ADxmdpDnfSdAO0Kc',
    appId: '1:372015866202:ios:e03c239805a6eda0531363',
    messagingSenderId: '372015866202',
    projectId: 'godevi-77a73',
    storageBucket: 'godevi-77a73.firebasestorage.app',
    iosBundleId: 'com.example.godeviApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiV8OXW2CuvnFPJZ4ADxmdpDnfSdAO0Kc',
    appId: '1:372015866202:ios:e03c239805a6eda0531363',
    messagingSenderId: '372015866202',
    projectId: 'godevi-77a73',
    storageBucket: 'godevi-77a73.firebasestorage.app',
    iosBundleId: 'com.example.godeviApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAsA-7EEY84ihoRQGWA1ZA31ixuzv1A-o',
    appId: '1:372015866202:web:d6c082c787031519531363',
    messagingSenderId: '372015866202',
    projectId: 'godevi-77a73',
    authDomain: 'godevi-77a73.firebaseapp.com',
    storageBucket: 'godevi-77a73.firebasestorage.app',
    measurementId: 'G-D698ML6NX2',
  );
}
